apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ehfu5dypn-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:83e5afed0485251fa3202ded8f39461a6b001b78@sha256:b1b5909fcc74bf8d452b44af478141e30ef9d3be6625d40d1544e5ebefa03aba
          name: container-image
