apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ehfu5dypn-go-gitops
  description: This is GitOps manifest for ehfu5dypn-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=ehfu5dypn-go
    backstage.io/kubernetes-id: ehfu5dypn-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ehfu5dypn-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ehfu5dypn-go
